### PR TITLE
33: Fixes and comments for udsr_dm_create

### LINKED ISSUE #33: Fixes and comments for udsr_dm_create

### PR DESCRIPTION
**Pull request by vd2org**

### CODE REVIEW

File: src/tools/usdr_dm_create.c [hunk 1]
```diff
@@ -20,6 +21,8 @@
 
 #include "../common/ring_buffer.h"
 
+#define DMCR "DMCR"
```
Comment (irodushka) [inline src/tools/usdr_dm_create.c]: Maybe LOG_TAG?

File: src/tools/usdr_dm_create.c [hunk 2]
```diff
@@ -157,6 +158,19 @@ void* freq_gen_thread_cf32(void* obj)
     return NULL;
 }
 
+bool print_device_temperature(pdm_dev_t dev)
+{
+    uint64_t temp[2];
```
Comment (irodushka) [inline src/tools/usdr_dm_create.c]: Why array?..  We use just uint64_t in usdr_dm_sensors

File: src/tools/usdr_dm_create.c [hunk 3]
```diff
@@ -157,6 +158,19 @@ void* freq_gen_thread_cf32(void* obj)
...
+    res = usdr_dme_get_uint(dev, "/dm/sensor/temp", temp);
+    if (res) {
+        USDR_LOG(DMCR, USDR_LOG_ERROR, "Unable to get device temperature: errno %d", res);
```
Comment (irodushka) [inline src/tools/usdr_dm_create.c]: better use USDR_LOG_WARNING for minor cases

File: src/tools/usdr_dm_create.c (hunk 1 above)
Comment (vd2org) [reply src/tools/usdr_dm_create.c]: ✅

File: src/tools/usdr_dm_create.c (hunk 3 above)
Comment (vd2org) [reply src/tools/usdr_dm_create.c]: ✅

File: src/tools/usdr_dm_create.c [hunk 4]
```diff
@@ -83,10 +85,13 @@ void* disk_read_thread(void* obj)
         char* data = ring_buffer_at(tbuff[i], idx);
         size_t res = fread(data, s_tx_blksz, 1, s_in_file[i]);
         if (res != 1) {
-            fprintf(stderr, "Can't read %d bytes! error=%zd\n",
-                    s_rx_blksz, res);
+            if(feof(s_in_file[i]))
+                USDR_LOG(LOG_TAG, USDR_LOG_INFO, "TX from file finished, EOF was reached");
+            else
+                USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Can't read %d bytes! res=%zd ferror=%d", s_rx_blksz, res, ferror(s_in_file[i]));
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c]: It should be `s_tx_blksz` instead `s_rx_blksz`

File: src/tools/usdr_dm_create.c [hunk 5]
```diff
@@ -171,6 +191,13 @@ enum {
     DD_RX_PATH,
 };
 
+static void usage(int severity, const char* me)
+{
+    USDR_LOG(LOG_TAG, severity, "Usage: %s '[-D device] [-f RX_filename] [-I TX_filename] [-c count] [-r samplerate] [-F format] [-C chmsk] [-S samples_per_blk] [-l loglevel] "
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c]: not all parameters are listed

File: src/tools/usdr_dm_create.c [hunk 6]
```diff
@@ -193,14 +220,13 @@ int main(UNUSED int argc, UNUSED char** argv)
     bool chmsk_alter = false;
     const char* fmt = "ci16";
     unsigned samples = 4096;
-    unsigned loglevel = USDR_LOG_TRACE;
+    unsigned loglevel = USDR_LOG_INFO;
     unsigned resync = 1;
     int noinit = 0;
-    unsigned dotx = 0;
-    unsigned dorx = 1;
+    unsigned dotx = 0; //means "do TX"
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c]: It would be better: `TX flag, enables TX if equal to 1`

File: src/tools/usdr_dm_create.c [hunk 7]
```diff
@@ -193,14 +220,13 @@ int main(UNUSED int argc, UNUSED char** argv)
...
+    unsigned dorx = 1; //means "do RX"
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c]: It would be better: RX flag, enables RX if equal to 1

File: src/tools/usdr_dm_create.c [hunk 8]
```diff
@@ -231,112 +260,152 @@ int main(UNUSED int argc, UNUSED char** argv)
...
+        //Set log level (0 - errors only -> 6+ - trace msgs)
         case 'l':
             loglevel = atof(optarg);
+            usdrlog_setlevel(NULL, loglevel);
             break;
+        //Set file name to store RX data (default: ./out.data)
         case 'f':
             filename = optarg;
             break;
+        //Set file name to read TX data (will emit sine if omited)
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c]: I think, it would be better `...will transmit sine...` instead `...will emit sine...

File: src/tools/usdr_dm_create.c [hunk 9]
```diff
@@ -231,112 +260,152 @@ int main(UNUSED int argc, UNUSED char** argv)
...
             break;
+        //Antenna configuration [0]
         case 'A':
             antennacfg = atoi(optarg);
             break;
+        //Don't stop on error
         case 'z':
             stop_on_error = false;
             break;
+        case 'h':
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c:460]: //Show usage

File: src/tools/usdr_dm_create.c [hunk 10]
```diff
@@ -358,17 +429,18 @@ int main(UNUSED int argc, UNUSED char** argv)
...
     if (res) {
-        fprintf(stderr, "Unable to create device: errno %d\n", res);
+        USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to create device: errno %d", res);
         return 1;
     }
 
     res = usdr_dme_get_u32(dev, "/ll/devices", (unsigned*)&devices);
     if (res) {
-        fprintf(stderr, "Defaulting devices to 1\n");
+        USDR_LOG(LOG_TAG, USDR_LOG_INFO, "Defaulting devices to 1");
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c]: What does this message mean?

File: src/tools/usdr_dm_create.c [hunk 11]
```diff
@@ -495,103 +566,102 @@ int main(UNUSED int argc, UNUSED char** argv)
...
+        USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to sync data streams: errno %d", res);
         if (stop_on_error) goto dev_close;
     }
 
+    //Start RX streaming
     if (dorx) {
         res = usds_rx ? usdr_dms_op(usds_rx, USDR_DMS_START, 0) : -EPROTONOSUPPORT;
         if (res) {
-            fprintf(stderr, "Unable to start data stream: errno %d\n", res);
+            USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to start data stream: errno %d", res);
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c]: It should to specify the stream direction, as example `Unable to start RX data stream`

File: src/tools/usdr_dm_create.c [hunk 12]
```diff
@@ -495,103 +566,102 @@ int main(UNUSED int argc, UNUSED char** argv)
...
             if (stop_on_error) goto dev_close;
         }
     }
+
+    //Start TX streaming
     if (dotx) {
         res = usds_tx ? usdr_dms_op(usds_tx, USDR_DMS_START, 0) : -EPROTONOSUPPORT;
         if (res) {
-            fprintf(stderr, "Unable to start data stream: errno %d\n", res);
+            USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to start data stream: errno %d", res);
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c]: It should to specify the stream direction, as example `Unable to start TX data stream`

File: src/tools/usdr_dm_create.c [hunk 13]
```diff
@@ -495,103 +566,102 @@ int main(UNUSED int argc, UNUSED char** argv)
...
+        USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to sync data streams: errno %d", res);
         if (stop_on_error) goto dev_close;
     }
 
 
+    //Set antenna configuration
     res = usdr_dme_set_uint(dev, "/dm/sdr/0/tfe/antcfg", antennacfg);
     if (res) {
-        fprintf(stderr, "Unable to set antcfg: errno %d\n", res);
+        USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to set antcfg: errno %d", res);
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c]: It would be better if we will describe the `antcfg`

File: src/tools/usdr_dm_create.c [hunk 14]
```diff
@@ -685,21 +758,21 @@ int main(UNUSED int argc, UNUSED char** argv)
...
-            fprintf(stderr, "Unable to stop data stream: errno %d\n", res);
+            USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to stop data stream: errno %d", res);
             goto dev_close;
         }
     }
     if (dotx) {
         res = usdr_dms_op(usds_tx, USDR_DMS_STOP, 0);
         if (res) {
-            fprintf(stderr, "Unable to stop data stream: errno %d\n", res);
+            USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to stop data stream: errno %d", res);
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c]: It should to specify the stream direction, as example `Unable to stop TX data stream`

File: src/tools/usdr_dm_create.c [hunk 15]
```diff
@@ -685,21 +758,21 @@ int main(UNUSED int argc, UNUSED char** argv)
...
-    usdr_dme_get_uint(dev, "/dm/debug/rxtime", temp);
     usdr_dme_get_uint(dev, "/dm/debug/rxtime", temp);
     //usdr_dme_get_uint(dev, usdr_dmd_find_entity(dev, "/dm/debug/rxtime"), temp);
 
+    //Stop RX&TX streams
     if (dorx) {
         res = usdr_dms_op(usds_rx, USDR_DMS_STOP, 0);
         if (res) {
-            fprintf(stderr, "Unable to stop data stream: errno %d\n", res);
+            USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to stop data stream: errno %d", res);
```
Comment (dtv-comp) [inline src/tools/usdr_dm_create.c]: It should to specify the stream direction, as example `Unable to stop RX data stream`

**Review by dtv-comp — CHANGES_REQUESTED** [review]

File: src/tools/usdr_dm_create.c (hunk 10 above)
Comment (irodushka) [reply src/tools/usdr_dm_create.c]: Who knows, it's @sergforce legacy)
